### ISSUE TITLE
ModuleNotFoundError =  not worke

### ISSUE THREAD

**Issue by Tiame7** [SinonApp/cansleep#2]
![photo_2024-02-01_01-23-29](https://github.com/SinonApp/cansleep/assets/158352980/b60159b2-9837-4ffd-ab53-95d9f3525cff)

```
Traceback (most recent call last):
  File "/home/subzero/cansleep/cansleep.py", line 6, in <module>
    from tools.brute import rtsp_bruter, dahua_bruter, hikka_bruter
  File "/home/subzero/cansleep/tools/brute.py", line 3, in <module>
    from connectors.hikvision import HikClient
  File "/home/subzero/cansleep/connectors/hikvision.py", line 1, in <module>
    from hikvisionapi import Client
ModuleNotFoundError: No module named 'hikvisionapi'

```

Can you tell me how to fix this bug?  at KALI LINUX

**Comment by seisdr** [comment]
run
```
pip install -r requirements.txt
```
at the root of this project.
You're missing "hikvisionapi" dependency
You can also install it by `pip install hikvisionapi`

**Comment by Tiame7** [comment]
> run
> 
> ```
> pip install -r requirements.txt
> ```
> 
> at the root of this project. You're missing "hikvisionapi" dependency You can also install it by `pip install hikvisionapi`

thank you .. its working now
