### ISSUE TITLE
not worked script

### ISSUE THREAD

**Issue by r0-xx** [SinonApp/cansleep#7]
I  can  Install all   requirements.txt python 3.8
I can run:

 python3.8 cansleep.py 

 
File "cansleep.py" , line 206 
match args.scanner:
            ^ 
SyntaxError: invalid syntax 

??? not worked

**Comment by MrRanMao** [comment]
Struct match/case used in python3.10 or higher.

You can upgrade python to 3.10 or change match/case to if/elif/else condition.

**Comment by r0-xx** [comment]
Thank you. Wokred on python 3.11
